### ISSUE TITLE
Bugs on master / melodic devel ?

### ISSUE THREAD

**Issue by tomlogan501** [dcentelles/dccomms_ros#1]
Hi,
I try to use this package from source and it occurred this :

```
../src/aqua-sim-ng/model/aqua-sim-rmac.cc: In member function ‘void ns3::AquaSimRMac::ProcessNDPacket(ns3::Ptr<ns3::Packet>)’:
../src/aqua-sim-ng/model/aqua-sim-rmac.cc:2404:12: error: unnecessary parentheses in declaration of ‘mach’ [-Werror=parentheses]
 2404 |   MacHeader(mach);
      |            ^
cc1plus: all warnings being treated as errors

Waf: Leaving directory `/home/tsimon/perso_catkin_ws/src/dccomms_ros/modules/ns-3-dev/build'
Build failed
 -> task in 'ns3-aqua-sim-ng' failed (exit status 1): 
	{task 140458501099856: cxx aqua-sim-rmac.cc -> aqua-sim-rmac.cc.1.o}
['/usr/bin/g++', '-O0', '-ggdb', '-g3', '-Wall', '-Werror', '-std=c++11', '-Wno-error=deprecated-declarations', '-fstrict-aliasing', '-Wstrict-aliasing', '-fPIC', '-pthread', '-I.', '-I..', '-DNS3_BUILD_PROFILE_DEBUG', '-DNS3_ASSERT_ENABLE', '-DNS3_LOG_ENABLE', '-DHAVE_SYS_IOCTL_H=1', '-DHAVE_IF_NETS_H=1', '-DHAVE_NET_ETHERNET_H=1', '-DHAVE_PACKET_H=1', '-DHAVE_IF_TUN_H=1', '-DHAVE_SQLITE3=1', '../src/aqua-sim-ng/model/aqua-sim-rmac.cc', '-c', '-o', '/home/tsimon/perso_catkin_ws/src/dccomms_ros/modules/ns-3-dev/build/src/aqua-sim-ng/model/aqua-sim-rmac.cc.1.o']
make[2]: *** [CMakeFiles/ns3.dir/build.make:61: CMakeFiles/ns3] Error 1
make[2] : on quitte le répertoire « /home/tsimon/perso_catkin_ws/build_isolated/dccomms_ros »
make[1]: *** [CMakeFiles/Makefile2:1893: CMakeFiles/ns3.dir/all] Error 2
make[1] : on quitte le répertoire « /home/tsimon/perso_catkin_ws/build_isolated/dccomms_ros »
make: *** [Makefile:144: all] Error 2
<== Failed to process package 'dccomms_ros': 
  Command '['/opt/ros/melodic/env.sh', 'make', '-j8', '-l8']' returned non-zero exit status 2
```
I'm using melodic from source with ubuntu 19.10.

On the branch melodic-devel I got this : 
```
../src/aqua-sim-ng/model/aqua-sim-signal-cache.cc: In member function ‘double ns3::AquaSimMultiPathSignalCache::ReflCoeff(double, double, double)’:
../src/aqua-sim-ng/model/aqua-sim-signal-cache.cc:423:23: error: ‘creal’ was not declared in this scope
  423 |   thetac=(s>s_bottom)?creal(acos(s/s_bottom)):acos(s/s_bottom);
      |                       ^~~~~
../src/aqua-sim-ng/model/aqua-sim-signal-cache.cc:429:20: error: ‘cexp’ was not declared in this scope; did you mean ‘exp’?
  429 |       return creal(cexp(sqrt(-1) * pi * (1-theta/thetac)));
      |                    ^~~~
      |                    exp

Waf: Leaving directory `/home/tsimon/perso_catkin_ws/src/dccomms_ros/modules/ns-3-dev/build'
Build failed
 -> task in 'ns3-aqua-sim-ng' failed (exit status 1): 
	{{task 139921035756560: cxx aqua-sim-signal-cache.cc -> aqua-sim-signal-cache.cc.1.o}}
['/usr/bin/c++', '-O0', '-ggdb', '-g3', '-Wall', '-Werror', '-std=c++11', '-Wno-error=deprecated-declarations', '-fstrict-aliasing', '-Wstrict-aliasing', '-fPIC', '-pthread', '-I.', '-I..', '-DNS3_BUILD_PROFILE_DEBUG', '-DNS3_ASSERT_ENABLE', '-DNS3_LOG_ENABLE', '-DHAVE_SYS_IOCTL_H=1', '-DHAVE_IF_NETS_H=1', '-DHAVE_NET_ETHERNET_H=1', '-DHAVE_PACKET_H=1', '-DHAVE_IF_TUN_H=1', '-DHAVE_SQLITE3=1', '../src/aqua-sim-ng/model/aqua-sim-signal-cache.cc', '-c', '-o', '/home/tsimon/perso_catkin_ws/src/dccomms_ros/modules/ns-3-dev/build/src/aqua-sim-ng/model/aqua-sim-signal-cache.cc.1.o']
NS3 modules: ns3-dev-antenna-debug;ns3-dev-flow-monitor-test-debug;ns3-dev-propagation-debug;ns3-dev-antenna-test-debug;ns3-dev-internet-apps-debug;ns3-dev-propagation-test-debug;ns3-dev-aodv-debug;ns3-dev-internet-apps-test-debug;ns3-dev-sixlowpan-debug;ns3-dev-aodv-test-debug;ns3-dev-internet-debug;ns3-dev-sixlowpan-test-debug;ns3-dev-applications-debug;ns3-dev-internet-test-debug;ns3-dev-spectrum-debug;ns3-dev-applications-test-debug;ns3-dev-lr-wpan-debug;ns3-dev-spectrum-test-debug;ns3-dev-aqua-sim-ng-debug;ns3-dev-lr-wpan-test-debug;ns3-dev-stats-debug;ns3-dev-aqua-sim-ng-test-debug;ns3-dev-lte-debug;ns3-dev-stats-test-debug;ns3-dev-bridge-debug;ns3-dev-lte-test-debug;ns3-dev-tap-bridge-debug;ns3-dev-buildings-debug;ns3-dev-mesh-debug;ns3-dev-test-debug;ns3-dev-buildings-test-debug;ns3-dev-mesh-test-debug;ns3-dev-test-test-debug;ns3-dev-config-store-debug;ns3-dev-mobility-debug;ns3-dev-topology-read-debug;ns3-dev-core-debug;ns3-dev-mobility-test-debug;ns3-dev-topology-read-test-debug;ns3-dev-core-test-debug;ns3-dev-mpi-debug;ns3-dev-traffic-control-debug;ns3-dev-csma-debug;ns3-dev-netanim-debug;ns3-dev-traffic-control-test-debug;ns3-dev-csma-layout-debug;ns3-dev-netanim-test-debug;ns3-dev-uan-debug;ns3-dev-dsdv-debug;ns3-dev-network-debug;ns3-dev-uan-test-debug;ns3-dev-dsdv-test-debug;ns3-dev-network-test-debug;ns3-dev-virtual-net-device-debug;ns3-dev-dsr-debug;ns3-dev-nix-vector-routing-debug;ns3-dev-wave-debug;ns3-dev-dsr-test-debug;ns3-dev-olsr-debug;ns3-dev-wave-test-debug;ns3-dev-energy-debug;ns3-dev-olsr-test-debug;ns3-dev-wifi-debug;ns3-dev-energy-test-debug;ns3-dev-point-to-point-debug;ns3-dev-wifi-test-debug;ns3-dev-fd-net-device-debug;ns3-dev-point-to-point-layout-debug;ns3-dev-wimax-debug;ns3-dev-flow-monitor-debug;ns3-dev-point-to-point-test-debug;ns3-dev-wimax-test-debug
CMake Error at CMakeLists.txt:142 (message):
  NS3 LIBRARY ns3-dev-antenna-debug NOT FOUND


-- Configuring incomplete, errors occurred!
See also "/home/tsimon/perso_catkin_ws/build_isolated/dccomms_ros/CMakeFiles/CMakeOutput.log".
See also "/home/tsimon/perso_catkin_ws/build_isolated/dccomms_ros/CMakeFiles/CMakeError.log".
<== Failed to process package 'dccomms_ros': 
  Command '['/opt/ros/melodic/env.sh', 'cmake', '/home/tsimon/perso_catkin_ws/src/dccomms_ros', '-DCATKIN_DEVEL_PREFIX=/home/tsimon/perso_catkin_ws/devel_isolated/dccomms_ros', '-DCMAKE_INSTALL_PREFIX=/opt/ros/melodic', '-DCMAKE_BUILD_TYPE=Release', '-G', 'Unix Makefiles']' returned non-zero exit status 1

Reproduce this error by running:
==> cd /home/tsimon/perso_catkin_ws/build_isolated/dccomms_ros && /opt/ros/melodic/env.sh cmake /home/tsimon/perso_catkin_ws/src/dccomms_ros -DCATKIN_DEVEL_PREFIX=/home/tsimon/perso_catkin_ws/devel_isolated/dccomms_ros -DCMAKE_INSTALL_PREFIX=/opt/ros/melodic -DCMAKE_BUILD_TYPE=Release -G 'Unix Makefiles'

Command failed, exiting.
```

I compile as such : 

```
sudo catkin_make_isolated --install -DCMAKE_INSTALL_PREFIX=/opt/ros/melodic -DCMAKE_BUILD_TYPE=Release
Base path: /home/tsimon/perso_catkin_ws
Source space: /home/tsimon/perso_catkin_ws/src
Build space: /home/tsimon/perso_catkin_ws/build_isolated
Devel space: /home/tsimon/perso_catkin_ws/devel_isolated
Install space: /opt/ros/melodic
Additional CMake Arguments: -DCMAKE_BUILD_TYPE=Release
```

With GCC : 
```
-- The C compiler identification is GNU 9.2.1
-- The CXX compiler identification is GNU 9.2.1
```

Could you add dockerfile to be sure it is stable ?

**Comment by tomlogan501** [comment]
On melodic-devel, after the trick to unconsider warnings as errors, here is what I get :
```
../src/aqua-sim-ng/model/aqua-sim-signal-cache.cc: In member function ‘double ns3::AquaSimMultiPathSignalCache::ReflCoeff(double, double, double)’:
../src/aqua-sim-ng/model/aqua-sim-signal-cache.cc:423:23: error: ‘creal’ was not declared in this scope
  423 |   thetac=(s>s_bottom)?creal(acos(s/s_bottom)):acos(s/s_bottom);
      |                       ^~~~~
../src/aqua-sim-ng/model/aqua-sim-signal-cache.cc:429:20: error: ‘cexp’ was not declared in this scope; did you mean ‘exp’?
  429 |       return creal(cexp(sqrt(-1) * pi * (1-theta/thetac)));
      |                    ^~~~
      |                    exp
```
Strange because complex.h is included.

**Comment by dcentelles** [comment]
Hi. Thank you for posting this issue. 
At the moment this package only works in **ubuntu 18.04** LTS with **gcc version 7.4.0.** and ROS Melodic.
Also, if you want to build dccomms_ros from source you should build [dccomms_ros_pkgs](https://github.com/dcentelles/dccomms_ros_pkgs), which includes dccomms_ros and its ros dependencies
If ubuntu 18.04 and ROS melodic are used you can install these packages directly from the ubuntu repositories:
`sudo apt-get install ros-melodic-dccomms-ros`
